name: NowCreates
favicon: null
layout_spectrum: 0.07096760882996023
typography_spectrum: 0.760638648411259
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.11001560161821544
  lightness: 0.25324962730519474
  saturation: 0.3913396771531552
  rhythmicContrast: 0.787134199636057
purpose: []
